name: rilog-be-dev.yml

on:
  push:
    branches: [ "develop" ]
    paths:
      - "backend/**"
      - '.github/workflows/rilog-be-dev.yml'

  pull_request:
    branches: [ "develop" ]
    paths:
      - "backend/**"
      - '.github/workflows/rilog-be-dev.yml'

jobs:
  build:
    name: Build Rilog Dev
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./backend

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Gradle Caching
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('backend/**/*gradle*', 'backend/**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build Rilog Service
        run: ./gradlew clean build -x test

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker Hub Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER_NAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker build & push
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          file: ./backend/Dockerfile-dev
          platforms: linux/arm64
          push: true
          tags: ${{ secrets.DOCKER_USER_NAME }}/${{ secrets.DOCKER_IMAGE }}:${{ secrets.DOCKER_TAG }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  deploy:
    name: Deploy Rilog Dev
    runs-on: self-hosted
    needs: build

    if: github.event_name == 'push'

    steps:
      - name: Deploy to server
        run: |
          cd /home/ubuntu
          ./deploy.sh
